name       : perl-html-tagset
version    : '3.20'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.20.tar.gz : adb17dac9e36cd011f5243881c9739417fd102fce760f8de4e9be4c7131108e2
homepage   : https://metacpan.org/pod/HTML::Tagset
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTML::Tagset - data tables useful in parsing HTML
description: |
    This module contains several data tables useful in various kinds of HTML parsing operations.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
