name       : perl-html-tagset
version    : 3.2
release    : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PETDANCE/HTML-Tagset-3.20.tar.gz : adb17dac9e36cd011f5243881c9739417fd102fce760f8de4e9be4c7131108e2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module contains data tables useful in dealing with HTML.
description: |
    This module contains data tables useful in dealing with HTML. It provides no functions or methods.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
